# BUILD to registry.cn-beijing.aliyuncs.com/imanager/ubuntu_condawithlib_cpu
FROM registry.cn-beijing.aliyuncs.com/imanager/ipse_base:latest

RUN curl -LO http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
 bash Miniconda3-latest-Linux-x86_64.sh -p /miniconda -b && \
 rm Miniconda3-latest-Linux-x86_64.sh

ENV PATH=/miniconda/bin:${PATH}
# RUN conda update -y conda

WORKDIR /home/supermap

COPY requirements-conda-cpu.yml ./

RUN conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/ && \
  conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/ && \
  conda config --set show_channel_urls yes && \
  conda env update -n base -f requirements-conda-cpu.yml && \
  conda clean --all -f -y
